### ISSUE TITLE
Measure data crash in hasHeartRateCapability()

### ISSUE THREAD

**Issue by AlexBravo** [android/health-samples#1]
NuppPointerException because capabilities is null where it should have not been:
How does this happen?
![Screen Shot 2021-06-22 at 5 13 47 PM](https://user-images.githubusercontent.com/488670/123015618-a191ed00-d37d-11eb-8015-f8a1188743fe.png)

This is where debugger stops:
![Screen Shot 2021-06-22 at 5 14 55 PM](https://user-images.githubusercontent.com/488670/123015623-a5257400-d37d-11eb-9aac-a4b6d8dc6a2e.png)

**Comment by garanj** [comment]
Thanks Alex!
