### ISSUE TITLE
Request: Water Lock example

### ISSUE THREAD

**Issue by adoxner** [android/health-samples#103]
Would love to see an example of how to enable water lock mode programmatically on Wear OS for a swim workout. I can't seem to find anything on it in the docs. Thanks!

**Comment by yschimke** [comment]
I haven't tried it, but there is an external sample here https://github.com/SimpleAppProjects/TouchLockHelper/blob/bb6a6f1254fd886eb1797297916134dce08e2cf2/app/src/main/java/com/thewizrd/touchlockhelper/MainActivity.kt

But it's possible this was for Wear 2?

**Comment by adoxner** [comment]
Thanks @yschimke this ended up working for me!

Basically:
1. Add `com.google.android.clockwork.settings.WATCH_TOUCH` permission to AndroidManifest.xml
2. `sendBroadcast(Intent("com.google.android.wearable.action.ENABLE_WET_MODE"))`

Got a little assist from archived docs [here](https://web.archive.org/web/20220105055932/https://developer.android.com/training/wearables/overlays/wet-mode)

**Comment by CoreFloDev** [comment]
It works on Samsung with wear os 4.0 but that doesn't trigger the samsung wet mode and only the touch screen deactivation. That lead to an other bug where disabling the non touch mode triggers bixby instead

**Comment by adoxner** [comment]
@CoreFloDev I am encountering the same issue with bixby. Have you found any workarounds?

**Comment by CoreFloDev** [comment]
Hi Adam,

I have been trying to enable the new water lock on Samsung devices there https://kotlinlang.slack.com/archives/C02GBABJUAF/p1697642156147229

But I don't know how to add the Samsung custom permission to my app. Maybe you know more about that?
