### ISSUE TITLE
Not detecting any data from the Galaxy Watch 4

### ISSUE THREAD

**Issue by danJarNC** [android/health-samples#13]
Is it possible for it to return all steps data from Samsung Health instead of just the phone steps using the HealthData?
I've connected Health Platform and I'm accurately reading the phone steps but steps from the watch are ignored. 

I'm using a ReadTimeGroupAggregatedDataRequest 

 builder.addCumulativeAggregationSpec(
                CumulativeAggregationSpec.builder(IntervalDataTypes.STEPS)
                        .setDataOrigin(DataOrigin.all())
                        .build());

I've tried changing DataOrigin to "all()" and "fromPlatform()" but it isn't changing anything.

Also when calling healthDataClient.getDevices(), only my phone is returned. 

Are watches even supported by the HealthData client? 

Thanks

**Comment by ithinkihaveacat** [comment]
@danJarNC Currently reading merged data is not supported. It will be supported in a future release.

**Comment by danJarNC** [comment]
Is there any estimated time when it will be supported? I'd like to feedback to my team, thanks!

**Comment by ithinkihaveacat** [comment]
It will be in the order of months, rather than weeks (or years).

Out of interest: what's your use case? Are you interested in just step count data, or other data as well?

**Comment by danJarNC** [comment]
Yes, we are initially interested in reading steps, distance and calories from Samsung Health, however, it's important that the watch data is included. 
Thanks

**Comment by danJarNC** [comment]
Hi, I'm also unable to read the data individually from the watch.
healthDataClient.getDevices() returns the watch uid successfully.

Then with ReadTimeGroupAggregatedDataRequest builder,

I set the watch uid like so:

 builder.addCumulativeAggregationSpec(
                CumulativeAggregationSpec.builder(IntervalDataTypes.STEPS)
                        .setDataOrigin(DataOrigin.fromDevice(device.getUid()))
                        .build());

But when I run the readTimeGroupAggregatedData, the callback always returns the same step data as the phone. 

Is there anything you can recommend that I could try?

**Comment by yayajoiiup** [comment]
I also try galaxy watch4, android health api always get the phone steps.
But for the user case, user see the total steps is (galaxy watch steps + phone steps) in Samsung health app.
It will confused user, and then said our app occur bug.
So hope api can get the galaxy watch steps or all steps not just phone steps.

![image](https://user-images.githubusercontent.com/48401730/154606631-8faa3e4c-c0e7-4dc4-bab4-f5283e6a1962.png)

**Comment by LeFal** [comment]
I have a similar problem. Please fix it.

**Comment by ithinkihaveacat** [comment]
Please see https://developer.android.com/guide/health-and-fitness/health-connect for these use cases.
