### ISSUE TITLE
EDA Sensor Data

### ISSUE THREAD

**Issue by luckyos-code** [android/health-samples#182]
Hello Health-Community,
since the new Pixel Watch 2 now includes continuous EDA sensor data, we are interested in the possibility of accessing these readings for our app and research plans. Is this SDK feature planned?

**Comment by breanatate** [comment]
There isn't a timeline for EDA sensor support in Health Services, but I will log this as a feature request.

Would having access to the readings in Health Connect be satisfactory? I can also log it as a feature request for that API.
