### ISSUE TITLE
All health services are not working

### ISSUE THREAD

**Issue by Srijita-Basak** [android/health-samples#23]
Hi! Are all the health services included in DataType working?ExerciseTypeCapabilities doesn't log all the data types. Am not getting the data for speed/pace/floors etc. Same goes for MeasureTypeCapabilities-it only returns HEART_RATE_BPM.  Do they work or there's something I'm missing out here. Please shed some light here sot hat I can be sure of what to follow next. Thanks in advance

**Comment by ithinkihaveacat** [comment]
The returned data types depend on the exercise type and the device. Some exercise types will return very few data types. RUNNING/HIKING/WALKING will typically return the most. (Though note the exercise type should reflect the type of exercise for the greatest accuracy, especially with respect to derived values like calories.)

The measure client will also typically returns very few data types. (I think on some devices is is limited to heart rate.)

**Comment by Srijita-Basak** [comment]
> 

Thank you so much for the reply. Thought so as well. Since when logging the measure client capabilities I can only see it returns HEART_RATE_BPM. Am using Samsung galaxy4 tho'. But even in exercise types RUNNING/HIKING/WALKING  not able to get speed/pace/incline distance datatypes etc. Is there anyway we can have one example added in the existing repository for speed/pace? Since there is not much am getting out of this. Is this a device issue? Am getting steps count, total calories, distance etc. I was wondering if I could get distance data, isn't the incline distance could be calculated in the same way?

**Comment by ithinkihaveacat** [comment]
If you add `DataType.SPEED` to the configs, it should be returned. Apply this (very hacky) diff to ExerciseSample: 

https://gist.github.com/ithinkihaveacat/ff926b20462cb8e4b3e59a4e6826224b

On a real device, this should produce output like:

```txt
2022-05-27 11:51:44.802 21058-21058/com.example.exercise D/qqqqqq: speed = 1.6660000085830688
2022-05-27 11:51:45.802 21058-21058/com.example.exercise D/qqqqqq: speed = 1.468000054359436
2022-05-27 11:51:46.822 21058-21058/com.example.exercise D/qqqqqq: speed = 1.2740000486373901
```

(You might need to use a real device. The synthetic mode doesn't seem to support speed.)

**Comment by Srijita-Basak** [comment]
> If you add `DataType.SPEED` to the configs, it should be returned. Apply this (very hacky) diff to ExerciseSample:
> 
> https://gist.github.com/ithinkihaveacat/ff926b20462cb8e4b3e59a4e6826224b
> 
> On a real device, this should produce output like:
> 
> ```
> 2022-05-27 11:51:44.802 21058-21058/com.example.exercise D/qqqqqq: speed = 1.6660000085830688
> 2022-05-27 11:51:45.802 21058-21058/com.example.exercise D/qqqqqq: speed = 1.468000054359436
> 2022-05-27 11:51:46.822 21058-21058/com.example.exercise D/qqqqqq: speed = 1.2740000486373901
> ```
> 
> (You might need to use a real device. The synthetic mode doesn't seem to support speed.)

Thank you so much for the response! Will check and try it in real device.

**Comment by garanj** [comment]
Did this solve the issue @Srijita-Basak ?

**Comment by Srijita-Basak** [comment]
> Did this solve the issue @Srijita-Basak ?

Yes! Got data this way in device. Thanks much
