### ISSUE TITLE
Question: Is there any way i can check which sports app(s) connected to Health Connect? 

### ISSUE THREAD

**Issue by akshpreetCbl** [android/health-samples#269]
I am also facing same issue, anybody have answer if health connect provides data when it sync data from another fitness app like "Google Fit". How to handle the case when user disabled the sinking data from third party app or user don't have any other third party app for sinking data, alert user for downloading third party app and enable sinking.

**Comment by breanatate** [comment]
The Health Connect API does not currently allow for this, but I've shared this with the product team as a feature request.
