### ISSUE TITLE
It is possible to obtain running and swimming metrics in the same exercise?

### ISSUE THREAD

**Issue by Desii99** [android/health-samples#28]
It is possible to obtain running and swimming metrics in the same exercise? I know I can get the running metrics by setting the type of sport like RUNNING and the swimming metrics by setting the type as SWIMMING_POOL, but can I get both at the same time? In certain sports this can be very useful as triathlon.

**Comment by ithinkihaveacat** [comment]
No, this is not possible. For e.g. triathlon you'll need to start an exercise with the SWIMMING type, then stop it and start another exercise with RUNNING, CYCLING, etc.

**Comment by Desii99** [comment]
Okay, thank you! :)
