### ISSUE TITLE
Problem adding more types of exercises

### ISSUE THREAD

**Issue by Desii99** [android/health-samples#29]
I can't add another exercise If I try to add another exercise apart from running and try to execute the other type of exercise I never take the data of the new exercise but those of running. Why could this happen? Is there an example where two types of exercise are implemented to observe that it could be failing?

**Comment by Desii99** [comment]
Also, I have configured the other type of exercise in the same way that I have configured the running exercise.

**Comment by garanj** [comment]
Are you able to share an example? Are you seeing any error messages?

You can configure the type of exercise using `setExerciseType`, as shown here in [HealthServicesManager](https://github.com/android/health-samples/blob/main/health-services/ExerciseSample/app/src/main/java/com/example/exercise/HealthServicesManager.kt#L129)

However, you should be sure to check that the device supports the exercise type you are requesting, and the data types you are requesting, using `capabilities`, as shown in [the sample](https://github.com/android/health-samples/blob/main/health-services/ExerciseSample/app/src/main/java/com/example/exercise/HealthServicesManager.kt#L57)
