### ISSUE TITLE
App updated needed

### ISSUE THREAD

**Issue by DevUNakamura** [android/health-samples#293]
Let me have a question to you.

I am developing Health Connect feature with referring your code.
I have an issue. Please see attachment file.

Whan I try to get to the permission, I meet this screen.
This issue is occurred on only Android 14 device.

Is there anything advice for solving this issue?
![Screenshot_20240828_204827](https://github.com/user-attachments/assets/c4b14d7a-d2b5-41c9-8b90-549ded16cef3)

**Comment by breanatate** [comment]
Hi,

Follow the steps [here](https://developer.android.com/health-and-fitness/guides/health-connect/migrate/migrate-from-android-13-to-14) to support Android 14.
