### ISSUE TITLE
Support for Galaxy Ring

### ISSUE THREAD

**Issue by ikemike** [android/health-samples#299]

**Comment by breanatate** [comment]
If this is a feature request, can you please file an [issue here](https://issuetracker.google.com/new?component=1056301&template=1581114)? This will help our team review and triage the request.

Please also specify if this request is for Health Connect or Health Services. If it is for the latter, Health Services is currently only supported on Wear OS devices.

**Comment by ikemike** [comment]
> If this is a feature request, can you please file an [issue here](https://issuetracker.google.com/new?component=1056301&template=1581114)? This will help our team review and triage the request.
> 
> Please also specify if this request is for Health Connect or Health Services. If it is for the latter, Health Services is currently only supported on Wear OS devices.

Thanks so much for the reply and apologies on the ambiguity. If you have a sec, could you give some guidance? There's limited documentation on the Galaxy Ring and the native Samsung Health app doesn't provide some of the features I'd like to see - like live heart rate tracking and SPO2.

**Comment by breanatate** [comment]
I'd suggest contacting [Samsung developer support](https://developer.samsung.com/dev-support). The ring is from Samsung and doesn't support Health Services, so there isn't any guidance we can provide from an Android Developer perspective.
