### ISSUE TITLE
Health Connect revoke function does not work in Android 14

### ISSUE THREAD

**Issue by LittleZombie** [android/health-samples#304]
I am using the revokeAllPermissions feature on phones with `Android 14 and above`, but I can still retrieve the previously granted permissions using permissionController.getGrantedPermissions. 

However, on phones with `Android 13 and below`, using the revokeAllPermissions function does not have this issue.

**Comment by breanatate** [comment]
Hi,
Is this an issue with the Health Connect Sample, or with the API? If the latter, do you mind opening an issue in the [Health Connect issue tracker](https://issuetracker.google.com/issues?q=status:open%20componentid:1232764&s=created_time:desc)? This will help our team better organize things.

**Comment by LittleZombie** [comment]
@breanatate  Thank you, I found that the issue has already been raised in the issue tracker.
https://issuetracker.google.com/issues/307685584
