### ISSUE TITLE
Health Connect API 1.1.0-alpha10 - getPackageName

### ISSUE THREAD

**Issue by BenLaKnet** [android/health-samples#314]
I tried this code to obtain package name of original data:

```

protected static void populateFromMeta(JSONObject obj, Metadata meta) throws JSONException
[...]
DataOrigin origin = meta.getDataOrigin();
        if (origin != null) {
            obj.put("sourceBundleId", origin.getPackageName());
        }
```

It is not running, I do not know why.
Is a declaration in AndroidManifest.xml or what ?

**Comment by weichenc** [comment]
To get the `dataOrigin`, you can just use `meta.dataOrigin` instead of `meta.getDataOrigin()`.

**Comment by BenLaKnet** [comment]
When I compiled, I obtained this message:

```
error: dataOrigin has private access in Metadata
        DataOrigin origin = meta.dataOrigin;
```

**Comment by BenLaKnet** [comment]
It is an Health Connect bug or ...?

**Comment by weichenc** [comment]
> When I compiled, I obtained this message:
> 
> ```
> error: dataOrigin has private access in Metadata
>         DataOrigin origin = meta.dataOrigin;
> ```
> 
> Is it possible that the problem comes from the AndroidManifest.xml and uses-permission file?

oh I just found out that you are written in Java instead of Kotlin. 
Could you show the error message of Logcat of "not running" and what is your expectation of "work"?

**Comment by BenLaKnet** [comment]
I have problems with Android Studio, my phone disconnect at every moment.
I develop with Cordova and Chrome.
I will try to show "Logcat".

**Comment by BenLaKnet** [comment]
If I add datas manually, that is ok with packagename.
If the datas comes from my Samsung gear S2 (heart_rate, steps, calories), synchronised with samsung Health, it returns undefined, but I have packagename in sourceBundleId into java code.
Strange.
I have to investigate...
