### ISSUE TITLE
Tracking Sleep Stages (LIGHT, DEEP) with Health Service

### ISSUE THREAD

**Issue by andimariadi** [android/health-samples#320]
I am currently using the Health Service API with Activity State to detect whether the user is ASLEEP or AWAKE. However, I would like to track additional sleep stages such as LIGHT and DEEP sleep.

Could you provide guidance or an example of how to detect these specific sleep stages using Health Service?

Thank you!

**Comment by andimariadi** [comment]
Thank you for your response!

However, I plan to use this application on Wear OS, which supports integration with Health Services. Is there another way to obtain sleep stage data like LIGHT or DEEP sleep directly on Wear OS, or do you have any other suggestions that might help in this regard?

Thank you so much for your assistance!

**Comment by breanatate** [comment]
Unfortunately, there aren't any other options that would use the Health Services API. I would recommend creating a mobile app that integrates with Health Connect, then using the [Wearable data layer API](https://developer.android.com/training/wearables/data/overview) to pass the data from the mobile app to your companion Wear OS app. 

The other possible alternative is to collect additional signals during sleep, such as accelerometer or other available sensors, to approximate sleep stages. We would not recommend this though, as it would have a substantial impact on battery. Additionally, there would be some challenges in scaling, as not all devices have the same sensors.

We have logged this as a feature request, and it is something the team will evaluate for future versions of Health Services!

**Comment by andimariadi** [comment]
Thank you so much for the explanation! I really appreciate the suggestions provided. I’m looking forward to the addition of new features that would allow access to sleep stages like LIGHT and DEEP Sleep in Health Services. I’m excited to see this in future updates.

Thanks again for your help!
