### ISSUE TITLE
[Health Connect Toolbox] 1.9 incorrectly write bp and weight.

### ISSUE THREAD

**Issue by b14cknc0d3** [android/health-samples#321]
**Which sample is this for?**
Health Connect Toolbox latest

**Describe the bug**
Health connect toolbox 1.9 incorrectly write bp and weight.

**Screenshots**
![2024-12-18 11 27 06 AM](https://github.com/user-attachments/assets/c5fecb90-90a8-4ca9-ad87-4bf5edd99e15)
![2024-12-18 11 27 13 AM](https://github.com/user-attachments/assets/5b888d24-c2b8-4a83-bad0-3be6ed6e2af0)

**Comment by aBozowski** [comment]
Thank you for raising this issue. The output value is always 10 and 20 correct? This appears to be an issue within the toolbox.

**Comment by b14cknc0d3** [comment]
Yes always 10  and 20 and weight is always 0 grams.

**Comment by aBozowski** [comment]
Please let us know if your issue is now resolved in [Toolbox 1.10](https://goo.gle/health-connect-toolbox). Please note weight is in Kg.

**Comment by b14cknc0d3** [comment]
Yes, it is now resolved.
