### ISSUE TITLE
Connection to service is not available for package 'com.google.android.wearable.healthservices' and action 'com.google.android.wearable.healthservices.ExerciseClient'.

### ISSUE THREAD

**Issue by sadaks-me** [android/health-samples#4]
E/ServiceConnection: Connection to service is not available for package 'com.google.android.wearable.healthservices' and action 'com.google.android.wearable.healthservices.ExerciseClient'.
E/ServiceConnection: Connection disconnected and maximum number of retries reached.
    java.util.concurrent.CancellationException: Service not available
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.connect(ServiceConnection.java:145)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.enqueue(ServiceConnection.java:203)
        at androidx.health.services.client.impl.ipc.internal.ConnectionManager.handleMessage(ConnectionManager.java:123)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:220)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by haozes** [comment]
same issue on Galaxy Watch 4 wearos3

**Comment by RKDeveloper12** [comment]
Experiencing the same issue.

**Comment by littleariel** [comment]
Same issue here.

**Comment by a-v-ebrahimi** [comment]
I have same issue on Galaxy Watch 4, WearOS.

**Comment by nkumar-ust** [comment]
I am also facing same issue on Samsung Wear watch 4 classic. Is Health Service APIs are not yet available on Samsung Watch 4/classic?

**Comment by garanj** [comment]
We've recently updated the samples for the `alpha02` release - there have been [quite a few changes](https://developer.android.com/jetpack/androidx/releases/health#health-services-client-1.0.0-alpha02) to the Health Services APIs since the Alpha01 release.

Are you able to try the updated sample?

**Comment by garanj** [comment]
Going to close this one out for now - if the issue remains with `alpha02`, can reopen.

**Comment by bensadiku** [comment]
@garanj I'm able to reproduce same issue even after alpha03. Is there a new release coming? It's been nearly a year since the last release...

**Comment by miloti-aliu** [comment]
@garanj same issue for me even on alpha03.

**Comment by artillerymans** [comment]
@miloti-aliu  same issue for me even on alpha10

**Comment by miloti-aliu** [comment]
@artillerymans this has been fixed on beta version. Currently I am using beta01 version and it works fine.

**Comment by artillerymans** [comment]
![image](https://user-images.githubusercontent.com/16060581/219997613-2fc03848-f803-4fd9-88d9-199df2cc5850.png)
Where is beta01? Has it been released?

**Comment by miloti-aliu** [comment]
Yes, you can find it here: https://developer.android.com/jetpack/androidx/releases/health

**Comment by breanatate** [comment]
@artillerymans the original issue was regarding the Health Services API (currently on beta02).

Are you seeing a similar error message on Health Connect (on alpha10)? Can you share the output?
