### ISSUE TITLE
 Is it possible to have a Sample for java version ?

### ISSUE THREAD

**Issue by sddog** [android/health-samples#45]

**Comment by breanatate** [comment]
Which API is this request for (Health Connect or Health Services)? Some of the Health Services documentation on developer.android.com has Java snippets. If you're able to support it, I would recommend using Kotlin as it promotes safer and more concise code. There are some helpful resources to get started with Kotlin if you already have extensive Java knowledge [here](https://developer.android.com/kotlin/add-kotlin).

If you're sticking with Java, for either sample you should be able to decompile the Kotlin code to Java within Android Studio (Tools > Kotlin > Show Kotlin Bytecode).
