### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by Anthony17serrato** [android/health-samples#46]
https://github.com/android/health-samples/blob/c0d875f1701fb21d6c224f4952fc5728c281ffb0/health-services/ExerciseSample/app/src/main/java/com/example/exercise/HealthServicesManager.kt#L203

comment suggests exerciseUpdateFlow is a shared flow when it is not actually a shared flow.

**Comment by ithinkihaveacat** [comment]
The sample is now updated, thanks for the report!
