### ISSUE TITLE
Question: Exercise Sample with Wear Compose

### ISSUE THREAD

**Issue by PLR2388** [android/health-samples#51]
Hello,
Are you planning to show how to use properly the exercise sample with wear compose? 
I don't know how to use Android Compose the right way with this example. I started with the Exercise Sample and I replaced xml views by Android Compose. However, I still keep the `ExerciseFragment` with almost all variables. The only thing I get rid of is `_binding` and `binding`. 
The thing I don't think is right in my code is that I store some functions from the fragment in my viewModel to call it in my screen (the composable function). 

To show you this, in `onViewCreated` of the `ExerciseFragment`, I did this : 
```
    viewModel.endExerciseCallback = {
            startEndExercise()
        }

        viewModel.pauseResumeCallBack = {
            pauseResumeExercise()
        }

        viewModel.forceStartExerciseCallback = {
            forceStartExercise()
        }

        viewModel.closeServiceCallBack = {
            stopChronometer()
            unbindViewsFromService()
        }
```

Can you explain me what's the right way to integrate the Exercise Sample using wear Compose without a mix of the 2 system?

Thank you!

**Comment by breanatate** [comment]
Hi, 

Yes, an updated sample using Wear Compose is in progress. Our approach is creating an instance of the ExerciseService in the ViewModel and binding to it in the ViewModel as well. Also in the ViewModel, we have all of the appropriate exercise methods, i.e: 
`fun pauseExercise() = exerciseService?.pauseExercise()`
 `fun endExercise() = exerciseService?.endExercise()`

Then, we access the ViewModel only within the NavHost, and reference the various exercise functions from within the NavHost, passing them into the appropriate screen, i.e:
`ExerciseScreen(
           onPauseClick = { composableScope.launch { viewModel.pauseExercise() } },
                onEndClick = { composableScope.launch { viewModel.endExercise() } },
                onResumeClick = { composableScope.launch { viewModel.resumeExercise() } },
                onStartClick = { composableScope.launch { viewModel.startExercise() } },
                serviceState = serviceState` 


Hope this helps! The updated sample should hopefully be published by November, let me know if you have any questions in the meantime.

**Comment by PLR2388** [comment]
Thank you breanatate, it's clearer now :) I'll wait to see the whole example. 
If I can ask you a question, can you look at my question on SO about saving the state and restore it when user go back to the app? Here's the link : https://stackoverflow.com/questions/73742226/how-to-save-and-update-a-state-in-a-foreground-service 

I'll be glad you look at it! Thank you 🙏

**Comment by storatle** [comment]
Breana,

do you know when you will publish the updated sample with exercise and wear compose? I'm waiting with anticipation. :-)

**Comment by akrulec** [comment]
Any updates on this? Thank you

**Comment by breanatate** [comment]
It's in progress--apologies for the delay. If there's a specific question, I may be able to answer it in the meantime @akrulec and @storatle

**Comment by akrulec** [comment]
Any documentations on how to actually bind a lifecycle service (any service) in Compose/ViewModel would be much appreciated. It's considered an anti-pattern right now: https://medium.com/androiddevelopers/viewmodels-and-livedata-patterns-antipatterns-21efaef74a54

**Comment by storatle** [comment]
No need for apologies @breanatate, I see you are working on it. It looks good :-)

**Comment by akrulec** [comment]
I have found a recommendation from the WearOS about services and ongoing activity: https://developer.android.com/codelabs/ongoing-activity#3 . However, when I try to run ExerciseService like that, the HealthServiceClient dies when the app is in the background:
```
W/ServiceConnection: Binder died for client:HealthServicesExerciseClient
W/ServiceConnection: WCS SDK Client 'HealthServicesExerciseClient' disconnected, retrying connection. Retry attempt: 0
    java.util.concurrent.CancellationException
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.lambda$cleanOnDeath$0$androidx-health-services-client-impl-ipc-internal-ServiceConnection(ServiceConnection.java:308)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection$$ExternalSyntheticLambda0.binderDied(Unknown Source:2)
        at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:305)
        at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:685)
```

I use Koin dependency injection:
```
fun provideHealthServicesClient(context: Context): HealthServicesClient {
    return HealthServices.getClient(context)
}
```

I create the HealthServicesManager as suggested in this sample:
```
class HealthServicesManager
constructor(healthServicesClient: HealthServicesClient, coroutineScope: CoroutineScope) {
    private val exerciseClient = healthServicesClient.exerciseClient
```

And my ExerciseService is a lifecycle service -- could this be the problem here?
```
class ExerciseService : LifecycleService() {
    private val healthServicesRepository: HealthServicesRepository by inject()
    private val healthServicesManager: HealthServicesManager by inject()
```

Thanks,

**Comment by breanatate** [comment]
Hi @akrulec thanks for pointing that out. Yes, not ideal or recommended--still playing around with overall structure and want to be sure it's set up correctly before it goes live. 

I think the LifecycleService is the right call, but the error you sent has been reported recently from a few other developers. Can you share the Health Services version so that I can investigate if it's the same issue?

`adb shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"`

**Comment by akrulec** [comment]
```
adb shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"
    versionCode=70695 minSdk=30 targetSdk=30
    versionName=0.8.16.446506339
    ```

**Comment by ithinkihaveacat** [comment]
@akrulec That version is close to a year old. Can you update it and try again?

You'll need to pair with a phone, and "transfer" an account from the phone from the watch so that Play Store on the watch will install the update.

If you're using Android Studio on an Intel Mac try this device (not sure whether it applies to other machines):

<img width="1112" alt="Screenshot 2023-02-01 at 10 57 59" src="https://user-images.githubusercontent.com/51244/216186824-a0ac9dc1-0906-48d4-adaf-bb2ba35aa1a2.png">

And this image:

<img width="1112" alt="Screenshot 2023-02-01 at 10 58 04" src="https://user-images.githubusercontent.com/51244/216186929-043e72b4-55fc-41bf-b3d4-ce0224786474.png">

(The more recent API 33 image has some problems.)

You should end up with:

```sh
$ adb shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"
versionCode=168741
versionCode=70695
versionName=0.14.30.480530839
versionName=0.8.16.446506339
```

**Comment by akrulec** [comment]
Thank you for the response! I'm running the demo in my emulator watch on Android Studio. It is Wear OS Small Round API 30. There is no option to create a devices with a system image that would have API 31.

**Comment by ithinkihaveacat** [comment]
@akrulec You need to select the Wear emulator, and then click "Pair Wearable". This will attempt to pair with an emulated phone (but that phone needs to be running API 31, not 33).

<img width="863" alt="Screenshot 2023-02-02 at 00 41 11" src="https://user-images.githubusercontent.com/51244/216202630-82b30a8d-ff9a-4cdb-93f1-b6c92420ee46.png">

**Comment by akrulec** [comment]
From what I understood the wear OS device was running a version of healthservices that was too old. My phone device is an actual android device that runs Android version 12, so API 32, and it does not have the healthservices at all:

```
adb devices
List of devices attached
R5CRB0RSNCD	device.  <- phone
emulator-5554	device.  <- emulator watch

nogavicka@totoro android-client % adb -s R5CRB0RSNCD shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"
nogavicka@totoro android-client % adb -s emulator-5554 shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName" 
    versionCode=70695 minSdk=30 targetSdk=30
    versionName=0.8.16.446506339
```

The binder crash I see is being reported on the emulator wear OS device:
```
W/ServiceConnection: Binder died for client:HealthServicesExerciseClient
W/ServiceConnection: WCS SDK Client 'HealthServicesExerciseClient' disconnected, retrying connection. Retry attempt: 0
    java.util.concurrent.CancellationException
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.lambda$cleanOnDeath$0$androidx-health-services-client-impl-ipc-internal-ServiceConnection(ServiceConnection.java:308)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection$$ExternalSyntheticLambda0.binderDied(Unknown Source:2)
        at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:305)
        at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:685)
```

I am running Android Studio Electric Eel | 2022.1.1
Build #AI-221.6008.13.2211.9477386, built on January 10, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 x86_64

Thank you

**Comment by ithinkihaveacat** [comment]
@akrulec You need to update the Health Services on the watch. To do this you need to pair it with a phone, by selecting the "Pair Wearable" function as shown here: https://github.com/android/health-samples/issues/51#issuecomment-1412981600. Then Play Store on the watch will be able to process updates.

**Comment by nogavicka** [comment]
Thank you for the explanation. I had no idea that's how the services got updated on the emulator. I paired the watch, but no update happened. So I navigated to the PlayStore in the emulator, and found Health Services, and selected update. Turns out, that now I have both version installed. I tried restarting the emulator, and that didn't help.
```
adb -s emulator-5554 shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"
    versionCode=168739 minSdk=30 targetSdk=30
    versionName=0.14.30.480530839
    versionCode=70695 minSdk=30 targetSdk=30
    versionName=0.8.16.446506339
```

I tried uninstalling, but it only removed one. It throws an error when trying to remove the other one:
```
adb -s emulator-5554 uninstall com.google.android.wearable.healthservices
Success

adb -s emulator-5554 shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"
    versionCode=70695 minSdk=30 targetSdk=30
    versionName=0.8.16.446506339

adb -s emulator-5554 uninstall com.google.android.wearable.healthservices                                                
Failure [DELETE_FAILED_INTERNAL_ERROR]
```

It looks like something is wrong with the underlying package names/versioning. It would be nice if the right version of the services would be available in the emulator with the next android studio update.

**Comment by ithinkihaveacat** [comment]
@nogavicka When there's two versions listed, the older one is typically a system version that cannot be removed. It should just be dormant though—with the new version in place, do you still get the error you reported at https://github.com/android/health-samples/issues/51#issuecomment-1411124197?

**Comment by ithinkihaveacat** [comment]
(And yes, we know it's not ideal to have to update health services like this, and are working on a fix.)

**Comment by akrulec** [comment]
> 

yes! if i update each time i reset the emulator, i don't run into the error anymore. thank you

**Comment by breanatate** [comment]
Closing this issue as the Compose-version is published. We'll continue to iterate and optimize--please let us know if you have any feedback!
