### ISSUE TITLE
Permission launcher is not working

### ISSUE THREAD

**Issue by saniazahan** [android/health-samples#55]
```
// My codes
        if (HealthConnectClient.isAvailable(context = this)){
            // Heath Connect is available and installed
            val healthConnectClient = HealthConnectClient.getOrCreate(context = this@MainActivity)
            Toast.makeText(this@MainActivity, "Lets capture some data", Toast.LENGTH_SHORT).show()
            // Create the permissions launcher.
            val requestPermissionActivityContract = healthConnectClient.permissionController.createRequestPermissionActivityContract()

            val requestPermissions =
                registerForActivityResult(requestPermissionActivityContract) { granted ->
                    if (granted.containsAll(PERMISSIONS)) {
                        // Permissions successfully granted
                    } else {
                        // Lack of required permissions
                    }
                }
        } else{
            Toast.makeText(this@MainActivity, "Health client not found", Toast.LENGTH_SHORT).show()
        }
```
Hi I am working on the demo healthconnect app and trying to add the permission launcher in the onCreate() method. But it is showing error for the ```createRequestPermissionActivityContract``` , ```registerForActivityResult``` etc. I could not find any suitable example to figure out the issues. Could you please suggest what  I am doing wrong. I am following this workflow 
https://developer.android.com/guide/health-and-fitness/health-connect/get-started

**Comment by breanatate** [comment]
Hello,

`PermissionController.createRequestPermissionActivityContract` was renamed to `PermissionController.createRequestPermissionResultContract` and made a static method in the alpha06 release. We're currently working on updating the documentation.

**Comment by raphael-dario** [comment]
permission launcher is not working as expected on my side, even using `PermissionController.createRequestPermissionResultContract()`
version: `androidx.health.connect:connect-client:1.0.0-alpha07`

it just calls immediately `registerForActivityResult` callback with no grants

```kotlin
    private var permissionsRequested = false
    private val permissions = setOf( HealthPermission.createReadPermission(StepsRecord::class) )
    private val requestPermissionActivityContract = PermissionController.createRequestPermissionResultContract()
    private val requestPermissions = registerForActivityResult(requestPermissionActivityContract) { granted ->
        if (!granted.containsAll(permissions)) {
            outputText("permissions not granted")
            return@registerForActivityResult
        }
        outputText("permissions granted")
        allPermissionsChecked()
    }
    
    private fun checkPermissions() = CoroutineScope(Dispatchers.IO).launch {
        StepCounterManager.healthConnectClient?.permissionController?.getGrantedPermissions(permissions)?.let { granted ->
            onPermissionsChecked(granted)
        }
    }
    
    private fun onPermissionsChecked(granted: Set<HealthPermission>) = CoroutineScope(Dispatchers.Main).launch {
        if (!granted.containsAll(permissions)) {
            if (permissionsRequested) { return@launch }

            outputText("requesting permissions...")
            permissionsRequested = true
            requestPermissions.launch(permissions) // doesn't show anything, calls immediately registerForActivityResult callback
            return@launch
        }
        allPermissionsChecked()
    }
    
   private fun allPermissionsChecked() = outputText("all permissions checked")
    
    override fun onResume() {
        super.onResume()
        if (!StepCounterManager.isHealthConnectAvailable(applicationContext)) { return }
        if (!permissionsRequested) { checkPermissions() }
    }
```

**Comment by johnhiott** [comment]
My first guess would be that the app is locked out.. meaning the app can no longer ask for permissions to Health Connect because the permissions prompt has been shown more than twice.

See the docs here: https://developer.android.com/guide/health-and-fitness/health-connect/get-started#step_4_request_permissions_from_the_user

```
If the user declines your permission request twice, your app is permanently locked out, and cannot request permissions again. 
If this happens to your app during development and testing, reset the permission request count by opening the Health Connect app and selecting allow all then remove all. 
Alternatively use adb to clear the cache of the Health Connect package.
```

However, I have noticed that Google Fit and other apps have been able to launch Health Connect after the 2nd try.
After combing through the documentation, I can not find any way of knowing when to attempt to ask for permissions or launch Health Connect.  

@breanatate Do you have and insight on this?

**Comment by breanatate** [comment]
That's correct that the app will be unable to request permissions after the user has denied twice. The Google Fit prompts also stop showing up for me after the 2nd attempt. Our recommendation is to also give users a direct path from your app to Health Connect to manage settings. 

```
val intent =
  context.packageManager.getLaunchIntentForPackage("com.google.android.apps.healthdata")
if (HealthConnectClient.isAvailable(context) && intent !== null) {
  context.startActivity(intent)
}
```

**Comment by johnhiott** [comment]
Thank you so much for your feedback!

I will add a direct path to Health Connect.

That is odd though, that Google Fit launches Health Connect after the 2nd try instead of the permissions screen and does not do this for you.

Thanks again.

**Comment by raphael-dario** [comment]
@johnhiott  thanks for your answer. I would think that after uninstalling the app from my phone, and then re-installing it would also reset the permissions requests count (like resetting permissions for any other app on android). seems that this is not the case and Health Connect keeps the permissions count even after uninstall (maybe by package name). I will attempt to clear the Health Connect cache and try again. although just be aware that it could be misleading to developers.

**Comment by breanatate** [comment]
Thanks @raphael-dario I've shared this feedback with the team and they are working on a solution.

In the interim, the best solution is to provide a "Manage Health Connect" button within settings (in addition to the initial Set Up/Connect button). That way, users can modify permissions even after they've enabled them. To reset the counter otherwise, the user would need to go into Health Connect and toggle the permissions for the particular app, and upon re-entering the app, the set-up flow should work again.

**Comment by aj-dt** [comment]
FWIW, I encountered this same behavior, and it turned out I was missing this intent filter:

```
<intent-filter>
    <action android:name="androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE" />
</intent-filter>
```

As described here:
https://developer.android.com/health-and-fitness/guides/health-connect/get-started

**Comment by coalacorey** [comment]
Also make sure you have copied the manifest permissions correctly (i.e. without any blank spaces) and that all Read/Write permissions line up with the actual permissions you define and request at runtime, otherwise the dialog will not show.
