### ISSUE TITLE
Launching Permissions Request stops working after 2 tries

### ISSUE THREAD

**Issue by jcwcmimik** [android/health-samples#59]
Subsequent attempts seem to just call back with an empty array. For HealthConnectSample, each different request seems to work twice, then ceases to function. After permissions have been denied twice, the user must navigate into Health Connect Settings and either toggle on and off access for the app, or remove access for all apps.

If this is intentional it would be good to have some programmatic way to check if requests are being blocked.

androidx.health.connect:connect-client:1.0.0-alpha06
Health Connect 0.1.1153.480892628.0-open_beta

Google Pixel 4a, Android 12, Build number SQ3A.220705.003.A1

**Comment by raphael-dario** [comment]
seems intentional according to the doc:

https://developer.android.com/guide/health-and-fitness/health-connect/get-started#step_4_request_permissions_from_the_user

_If a permission is denied more than twice, you will be locked out (the permission request will no longer appear)._

**Comment by breanatate** [comment]
Yes, this is intentional. Thank you for your feedback, we have tracked this internally.
