### ISSUE TITLE
Missing synthetic testing instructions for health events

### ISSUE THREAD

**Issue by dshokouhi** [android/health-samples#60]
I was wondering if there was a way for us to test the new Fall Detected health event by using the synthetic testing instructions. I would like to test how the data works with our application but I don't see any instructions on how to do that. Can I test the event by taking my watch off and dropping it in my lap or will the on body detection prevent that?

**Comment by breanatate** [comment]
Hi, yes. Once you enable synthetic providers, you should be able to use:

`$ adb shell am broadcast \
-a "whs.synthetic.user.FALL_OVER" \
com.google.android.wearable.healthservices`

**Comment by dshokouhi** [comment]
Thank you so much! We can close this issue now if you like unless it should remain open until the docs are updated?

**Comment by ithinkihaveacat** [comment]
Docs update is in progress; should make it to the public site in a week. Thanks for raising this!
