### ISSUE TITLE
Trying to get DataType.STEPS_DAILY  -> crash with missing permission

### ISSUE THREAD

**Issue by vkjambit** [android/health-samples#80]
Instead of getting the heart-rate in the PassiveData example i wanted to get the daily step count. 
This always crashes:

_FATAL EXCEPTION: main
Process: com.example.passivedata, PID: 6322
java.lang.Exception: Missing permissions
at androidx.health.services.client.impl.internal.StatusCallback.onFailure(StatusCallback.kt:42)
at androidx.health.services.client.impl.internal.IStatusCallback$Stub.onTransact(IStatusCallback.java:80)
at android.os.Binder.execTransactInternal(Binder.java:1159)
at android.os.Binder.execTransact(Binder.java:1123)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1294ec, Dispatchers.Main.immediate]
_

I'm testing on Samsung Galaxy Watch 4. 
I of course also changed the getCapapities call....

**Comment by garanj** [comment]
Thanks for the report.

Which permissions are you requesting?

Heart rate required the BODY_SENSORS permission, but steps will require the ACTIVITY_RECOGNITION permission, both in the manifest  and in the runtime request.

Did you modify the sample to include those?

**Comment by vkjambit** [comment]
thanks. this solved it.

**Comment by Agusioma** [comment]
Hello @garanj, is there a page where we can find the necessary permissions for the respective Data types. Like [this](https://developer.android.com/guide/health-and-fitness/health-connect/data-and-data-types/data-types) one perhaps.

**Comment by breanatate** [comment]
Hi @Agusioma we're actively working on adding this to the documentation.
