### ISSUE TITLE
Can't prepareExercise on Wear OS 3.5 device (galaxy watch 5)

### ISSUE THREAD

**Issue by nolza95** [android/health-samples#83]
I am using exercisesamplecompose on emulator and galaxy watch 5. emulator is ok. but it doesn't work on real device
first of all, It can't get locationAvailability(GPS), so keep showing ProgrssBar, 
anyway when I proceed GO without properly prepared, it does not seems like binding foregroundservice to activity, when I press STOP, it doesn't show unbind on Logcat, and when I press RESTART, app is terminated forcibly and log tell me there's no active exercise

**Comment by nolza95** [comment]
I checked exercisesamplecompose with other galaxy watch 4 device, It also does not work. is it just for emulator as a model?

**Comment by Agusioma** [comment]
@breanatate Galaxy community, we would appreciate if this is fixed.
