### ISSUE TITLE
Not able to get List of response.records 

### ISSUE THREAD

**Issue by jimmytrivedi** [android/health-samples#86]
There are many data in my Google Fit, but not able to get it, even I try to modify the data.

**Comment by breanatate** [comment]
Hi there,

Is this an issue with a particular sample? Otherwise, do you mind filing a bug in our [Issue Tracker](https://buganizer.corp.google.com/issues/new?component=1056301&template=1581114) with more information?

**Comment by jimmytrivedi** [comment]
Hi @breanatate 

I feel that this is a bug. The issue tracker link which you suggested, that is for partner with Google. So I used public one and reported the issue.

Issue: https://issuetracker.google.com/issues/274144813
