### ISSUE TITLE
Request for assistance in retrieving sleep data from Health Connect API

### ISSUE THREAD

**Issue by SagarArshikweb** [android/health-samples#90]
Subject: Request for assistance in retrieving sleep data from Health Connect API

Dear Google team,

I am writing to seek your assistance in retrieving sleep data from the Health Connect API. I have attempted to retrieve this data by specifying the startTime and endTime parameters as blank, but have been unsuccessful.

I would appreciate it if you could guide me on how to retrieve sleep data from the Health Connect API, including the required parameters and their respective values. I understand that there are two types of sleep data available: sleepStage and sleepSession.

I am writing to share with you a sample of the data that we have collected thus far.

Sleep Stage 
[{"endTime":{},"endZoneOffset":{},"metadata":{"clientRecordVersion":0,"dataOrigin":{"packageName":"androidx.health.connect.client.devtool"},"device":{"type":0},"id":"20848e26-1061-4ebc-b8ae-32a43249abbe","lastModifiedTime":{}},"stage":1,"startTime":{},"startZoneOffset":{}}]

Sleep Session 
[{"endTime":{},"endZoneOffset":{},"metadata":{"clientRecordVersion":0,"dataOrigin":{"packageName":"androidx.health.connect.client.devtool"},"device":{"type":0},"id":"f38a99b5-e72f-4148-a937-b6ca587ba690","lastModifiedTime":{}},"notes":"Notes","startTime":{},"startZoneOffset":{},"title":"Title"}]

Thank you for your time and assistance.

Sincerely,
Sagar

**Comment by breanatate** [comment]
Hello, we have an example of retrieving sleep data in our [sample](https://github.com/android/health-samples/blob/6b1ffc4ccc69c486ffce59fd712bad8d78e86d6f/health-connect/HealthConnectSample/app/src/main/java/com/example/healthconnectsample/data/HealthConnectManager.kt#L312). 

You can also consult the documentation on reading sleep sessions [here](https://developer.android.com/reference/kotlin/androidx/health/connect/client/records/SleepSessionRecord).

Please let me know if you have any additional questions.

**Comment by SagarArshikweb** [comment]
Subject: Issue retrieving sleep data from Health Connect app on Android
device

Hello Google team,

I am writing to report an issue that I am experiencing with the Health
Connect app on my Android device. Specifically, I am trying to retrieve
sleep data from the app, but I am not seeing the time and duration
information for each sleep session.

I have checked my device's settings and the Health Connect app settings,
but I cannot seem to find a solution to this issue. I am wondering if this
is a known bug or issue with the app, or if there is something else that I
can try to resolve this problem.

For reference, I am using [SAMSUNG M21, ANDROID OS 12] and the latest
version of the Health Connect app. Any assistance or guidance you can
provide would be greatly appreciated.

For reference sleep data
Sleep Stage
[{"endTime":{},"endZoneOffset":{},"metadata":{"clientRecordVersion":0,"dataOrigin":{"packageName":"androidx.health.connect.client.devtool"},"device":{"type":0},"id":"20848e26-1061-4ebc-b8ae-32a43249abbe","lastModifiedTime":{}},"stage":1,"startTime":{},"startZoneOffset":{}}]

Thank you for your time and attention to this matter.

Sincerely,
Sagar Vasoya

**Comment by breanatate** [comment]
Can you share the code you've written to read sleep data?

**Comment by breanatate** [comment]
Hi Sagar, checking in. Were you able to read sleep data from Health Connect? Or alternatively, are you able to provide the code you've written to read sleep data?

Thanks!

**Comment by SagarArshikweb** [comment]
Yes, we are getting data properly and using health connect.
Thanks google team for always support.
