### ISSUE TITLE
I try get data with SPO2, VO2. VO2_MAX .But i don’t get on Sam Sung watch 4?

### ISSUE THREAD

**Issue by lambui09** [android/health-samples#93]
from https://developer.android.com/reference/kotlin/androidx/health/services/client/data/DataType#VO2_MAX() . All return 0

**Comment by breanatate** [comment]
Hello,

SpO2 is not currently supported. Can you provide more information about your use case so I can pass the details back to the engineering team?

For VO2_MAX(), how long was the exercise length for your test? Some devices require many minutes of exercise (~20 minutes) to calculate and then return a VO2 Max value. Additionally (one the time conditions are met), Health Services returns a VO2_Max value when flush() is called. This happens either by manually calling flush or when the exercise is paused or stopped.

**Comment by lambui09** [comment]
thank you for your support. with steps, when i run 20 minus, I get ManagerSensor, but it update lately. Is it possible to update realtime steps?

**Comment by breanatate** [comment]
You can use Health Service's Exercise Client to get real time steps as part of a Running exercise. Our Exercise Samples are a good place to start, as they record a Running exercise, you would just need to also request steps as a data type.

To clarify, is this for steps as part of an app? Or are you looking to integrate steps into something like a watchface?

**Comment by arpanevontech** [comment]
I am using one plus watch 2 but i am not able to read the data from spo2 sensor how can i read spo2 data from the watch .
can you please help me in this @breanatate

**Comment by breanatate** [comment]
@arpanevontech please file a feature request [here](http://issuetracker.google.com/issues/new?component=1056301&template=1581114)

**Comment by arpanevontech** [comment]
Hi @breanatate  i raised the issue which i am facing can you please check and talk to your team regarding this.
thanks for your time and support
